Added support for exact matching of Arabic and Chinese
OCHA-DAP/hdx-python-country pull request #15
Opened 2023-03-23 16:39 UTC by SivanC

Fixes an issue where Arabic and Chinese text were not being matched (e.g. 中国 for China). Solves issue #9. 

I resolved the issue by adding two conditionals to `get_iso3_country_code()` that detect each character set respectively and search through the dictionary to retrieve the ISO3 code, or else return None like usual. 

When Arabic or Chinese text was previously passed into the function, the `if countryupper.isupper()` conditional would return False, and the function would return None. 

I think this is the only method that needed this fix, as it's the only method in `country.py` that takes a generic country string as opposed to ISO3/ISO2/M49 and then converts it, but if I missed another method then this fix should be able to be adapted to it easily.

2023-03-23 20:56 UTC, mcarans requested changes
Thanks for your PR. It looks good. The only minor change that is needed is to the formatting. Please can you fix the errors below (by running Black from the project root).

```
lint: commands[0]> flake8 --color=always src tests
  src/hdx/location/country.py:750:20: BLK100 Black would make changes.
                  if countriesdata["countries"][country]["#country+alt+i_zh+name+v_unterm"] == countryupper:
                     ^
  tests/hdx/location/test_country.py:458:70: BLK100 Black would make changes.
              Country.get_iso3_country_code("المملكة العربية السعودية")
```

Also I just want to check with you about the unicode range for Arabic. On [Wikipedia](https://en.wikipedia.org/wiki/Unicode_block), I see "U+0600..U+06FF", but you have used a smaller range "\u0621-\u064A". How did you come up with the more specific smaller range?

2023-03-26 21:28 UTC, SivanC commented
Hi, sorry for my delayed response. I got the unicode range through browsing a few stack overflow links, didn't think to check Wikipedia, I'll update with the larger range.

2023-03-27 01:32 UTC, mcarans commented
Nearly there. Just one more lint error to fix. 
```
  lint: commands[0]> flake8 --color=always src tests
  tests/hdx/location/test_country.py:458:70: BLK100 Black would make changes.
              Country.get_iso3_country_code("المملكة العربية السعودية")
```

You can run what is run in the GitHub Action locally by installing and running tox. This reminds me to write some contribution guidelines to make it easier for new contributors.

2023-03-27 03:04 UTC, SivanC commented
Noted, I ran Black in the root directory but it didn't pick that up, maybe I ran it wrong.

2023-03-27 03:53 UTC, SivanC commented
Thanks for the pointers on using tox to run the workflow, I think I did it correctly, fixed the test file and then everything passed successfully.

2023-03-27 04:41 UTC, merged

2023-03-27 04:42 UTC, mcarans commented
Thanks very much for your PR which I have now merged.

2023-03-27 05:52 UTC, SivanC commented
You're welcome!